CREATE TABLE OUTBOX_EVENT (
    id UUID PRIMARY KEY,
    event_type TEXT NOT NULL,
    payload TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dispatched BOOLEAN NOT NULL DEFAULT FALSE
);
