CREATE TABLE OUTBOX_EVENT (
    id UUID PRIMARY KEY,
    event_type TEXT NOT NULL,
    venue_id TEXT NOT NULL,
    payload TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dispatched BOOLEAN NOT NULL DEFAULT FALSE
);
